version: "3"

services:
  gogs:
    image: gogs/gogs
    volumes:
      - ./gogs/data:/data
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=apache_session
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
  apache:
    build: apache/.
    ports:
      - "8443:8443"
    volumes:
      - ./apache/httpd/conf.d:/etc/httpd/conf.d
      - ./apache/httpd/tls:/etc/httpd/tls
      - ./apache/html:/var/www/html
      - ./apache/passwd:/etc/httpd/passwd
    depends_on:
      - gogs
      - mysql
volumes:
  mysql-data:
