version: "3"

services:
  gitlab:
    container_name: gitlab-container
    image: 'gitlab/gitlab-ee:latest'
    # restart: always
    # hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost'
    ports:
      - '443:443'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=apache_session
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
  apache:
    build: apache/.
    ports:
      - "8443:8443"
    volumes:
      - ./apache/httpd/conf.d:/etc/httpd/conf.d
      - ./apache/httpd/tls:/etc/httpd/tls
      - ./apache/html:/var/www/html
      - ./apache/passwd:/etc/httpd/passwd
    depends_on:
      - gitlab
      - mysql
volumes:
  mysql-data:
